### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by fguisso** [ZupIT/horusec-platform#109]
Hey guys, I'm back, try to work on this option, but I can't find de API documentation, there is an option to communicate with the API yet in version 2?

https://github.com/ZupIT/horusec/issues/104#issuecomment-721756512

**Comment by nathannascimentozup** [comment]
Hi @fguisso, I'm reading the thread to see how I can help

**Comment by nathanmartinszup** [comment]
Hi, @fguisso. Sorry for the delay.

If you are looking for api documentation, each service has a swagger with all application routes.

Unfortunately in horusec's own documentation page, we still don't have this information. 
But it's a great idea to add in the future.
