### ISSUE TITLE
SOMETHING UNEXPECTED HAPPENED, TRY AGAIN

### ISSUE THREAD

**Issue by jooeji** [ZupIT/horusec-platform#145]
1. git clone https://github.com/ZupIT/horusec-platform.git
2. cd horusec-platform && make run-web
3. but login failed 
4. notice:SOMETHING UNEXPECTED HAPPENED, TRY AGAIN
![image](https://user-images.githubusercontent.com/12831513/128128880-97cbeae5-883d-40d0-8302-3aeaaa24f090.png)
```
2021/08/04 07:43:43 /go/pkg/mod/github.com/!zup!i!t/horusec-devkit@v1.0.3/pkg/services/database/database.go:134 ERROR: duplicate key value violates unique constraint "accounts_email_key" (SQLSTATE 23505)
[4.005ms] [rows:0] INSERT INTO "accounts" ("account_id","email","password","username","is_confirmed","is_application_admin","created_at","updated_at") VALUES ('76b36138-7d30-4124-b833-0692495f097b','dev@example.com','$2a$10$EgIQuPFAN1Jv4EcE3.VL5uTNmRfoHULYcei/5ngAW1XOa37Jt8Hru','dev',true,false,'2021-08-04 07:43:43.339','2021-08-04 07:43:43.339')
panic: {ERROR_BROKER} failed to connect: dial tcp 127.0.0.1:5672: connect: connection refused

```

**Comment by wiliansilvazup** [comment]
Hello @jooeji 
Tnks for you feedback!

We really have a problem with horusec's all-in-one image!
Until it is fixed, we suggest you upload the web application using the command below:
```
make install
```

**Comment by jooeji** [comment]
i did `make install` ,but the container `horuszup/horusec-messages` is not up,
the errors 
```
panic: {ERROR_BROKER} failed to connect: dial tcp 172.23.0.3:5672: connect: connection refused

goroutine 1 [running]:
main.main()
        /messages/cmd/app/main.go:33 +0x7d
time="2021-08-05T03:31:26Z" level=panic msg="{MAILER invalid mailer config}" error="password: cannot be blank; username: cannot be blank."
panic: (*logrus.Entry) 0xc0001fee00

```

**Comment by wiliansilvazup** [comment]
is normal, because [you not pass configuration of the smtp](https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/#step-2-check-the-uninitiated-services), in this case is not necessary if you not want

**Comment by jooeji** [comment]
{ERROR_BROKER} failed to connect: dial tcp 172.23.0.3:5672: connect: connection refused
----------------
all container has the error, is normal?

**Comment by wiliansilvazup** [comment]
all containers is not normal, this IP `172.23.0.3` you change in docker-compose file ? And message broker(RabbitMQ) is enable in this IP and port ?

**Comment by wiliansilvazup** [comment]
by default horusec makes all services available in its docker-compose in IP `127.0.0.1` or `localhost` any change for IP or host you can change in docker-compose environments variables and install again

**Comment by jooeji** [comment]
all default config, i did not change default config, this IP 172.23.0.3 is RabbitMQ ip 

i try change docker-compose environments again

**Comment by jooeji** [comment]
```
2021-08-10 01:27:42.398852+00:00 [info] <0.1217.0> accepting AMQP connection <0.1217.0> (172.24.0.5:43442 -> 172.24.0.3:5672)
2021-08-10 01:27:42.401659+00:00 [info] <0.1217.0> connection <0.1217.0> (172.24.0.5:43442 -> 172.24.0.3:5672): user 'guest' authenticated and granted access to vhost '/'
2021-08-10 01:27:42.442907+00:00 [warn] <0.1217.0> closing AMQP connection <0.1217.0> (172.24.0.5:43442 -> 172.24.0.3:5672, vhost: '/', user: 'guest'):
2021-08-10 01:27:42.442907+00:00 [warn] <0.1217.0> client unexpectedly closed TCP connection

```

**Comment by jooeji** [comment]
horusec-auth errors 
```
ERROR: duplicate key value violates unique constraint "accounts_email_key" (SQLSTATE 23505)
```

**Comment by jooeji** [comment]
did it ,This error is caused by environment variables not taking effect

**Comment by wiliansilvazup** [comment]
From what I understand you found a problem in the settings of the environment variables on your machine and the problem was solved, correct?

**Comment by jooeji** [comment]
Yes, but I suggest you can be more flexible about the configuration of environment variables，
-----------
https://horusec.io/docs/tutorials/how-to-run-the-web-application-on-other-host/#step-3-configure-horusec-manager
![image](https://user-images.githubusercontent.com/12831513/129126120-35e35e10-2fa6-4867-9a3e-a24d53194e07.png)
