### ISSUE TITLE
Error When Add Extra ENV

### ISSUE THREAD

**Issue by kmandagie** [ZupIT/horusec-platform#451]
**What happened**:
When I used Extra ENV in Helm I and apply it I get htis error
`Error: UPGRADE FAILED: YAML parse error on horusec-platform/templates/deployments/auth.yaml: error converting YAML to JSON: yaml: line 83: did not find expected key`
**What you expected to happen**:
Success to apply the helm
**How to reproduce it (as minimally and precisely as possible)**:
add extraEnv in auth section
```yaml
    extraEnv: : 
    - name: HORUSEC_LDAP_PORT
      value: 636
```
**Anything else we need to know?**:
I think the problem is caused by this  section
https://github.com/ZupIT/horusec-platform/blob/main/deployments/helm/horusec-platform/templates/deployments/auth.yaml#L111
the number of indent is suppose to be 10 I think
**Environment**:
- Horusec version (use `horusec version`): Helm Horusec  2.16.2
- Operating System: Linux Mint 20.01
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:

**Comment by nathanmartinszup** [comment]
Hello @kmandagie!

Installed the helm chart with the extra var and had no problems. In the example you sent it has two `: :`.

Can you remove it and try again:
```
    extraEnv:
    - name: HORUSEC_LDAP_PORT
      value: 636
```

**Comment by kmandagie** [comment]
I still get the same error 

![image](https://user-images.githubusercontent.com/26500504/143818491-abc2cf6f-9753-46b6-801a-4f8d2e92d728.png)

**Comment by nathanmartinszup** [comment]
We are checking what happened and we'll get back to you as soon as possible.

Thanks for the contribution!

**Comment by nathanmartinszup** [comment]
Hi @kmandagie!

Sorry for the delay, we're been really busy this days. 

I opened a pull request #462 that fixes the nindent problem and also adds the ldap env vars by default in the helm files.

The ldap envs can be found in the global session in the values file: 

![ldap global-values](https://user-images.githubusercontent.com/63246935/145042420-dff1a302-5ac0-4a5c-8c00-0d315d317c69.png)

Here's as example how to use the extra env vars:

![extra-env-example](https://user-images.githubusercontent.com/63246935/145042064-478ed4fd-871f-43e5-bdf0-9792f89584b0.png)

Again thanks for your contribution and feedback!

**Comment by kmandagie** [comment]
Hi @nathanmartinszup thank you for your hard work.  yeah, I think the problem is solved with this method.  sorry I missed your reply before.
